export const FETCH_ORDEROFFLINE_REQUEST = 'FETCH_ORDEROFFLINE_REQUEST';
export const FETCH_USERDATA_REQUEST = 'FETCH_USERDATA_REQUEST';
export const FETCH_ROUTELIST_REQUEST = 'FETCH_ROUTELIST_REQUEST';
export const THEME_COLOR_TYPE = 'THEME_COLOR_TYPE';